# This file was generated by GoReleaser. DO NOT EDIT.
cask "nuntius" do
  name "nuntius"
  desc "AI-powered commit message generator TUI"
  homepage "https://github.com/crazzyghost/nuntius"
  version "0.0.6-alpha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nuntius"

  on_macos do
    on_intel do
      url "https://github.com/crazzyghost/nuntius/releases/download/v#{version}/nuntius_#{version}_darwin_amd64.tar.gz"
      sha256 "39690e152573c6c95c40f284f8763ba9851f40ce140073a81dcbb575d5068813"
    end
    on_arm do
      url "https://github.com/crazzyghost/nuntius/releases/download/v#{version}/nuntius_#{version}_darwin_arm64.tar.gz"
      sha256 "f081bbad0a572db81e60a0f45720d98c2551fbf9c9fc077282aa7baaae97831d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crazzyghost/nuntius/releases/download/v#{version}/nuntius_#{version}_linux_amd64.tar.gz"
      sha256 "48b34703ba255f81206a5f90746bd29296e1f0dc24411a56f357b8812fdad2e1"
    end
    on_arm do
      url "https://github.com/crazzyghost/nuntius/releases/download/v#{version}/nuntius_#{version}_linux_arm64.tar.gz"
      sha256 "7c0064b451aff814338c747608c453b629e3e0b5d0c479dbe63908353e573963"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nuntius"]
    end
  end

  # No zap stanza required
end
