# This file was generated by GoReleaser. DO NOT EDIT.
cask "nuntius" do
  name "nuntius"
  desc "AI-powered commit message generator TUI"
  homepage "https://github.com/crazzyghost/nuntius"
  version "0.0.1-alpha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nuntius"

  on_macos do
    on_intel do
      url "https://github.com/crazzyghost/nuntius/releases/download/v#{version}/nuntius_#{version}_darwin_amd64.tar.gz"
      sha256 "db7ebb3e2f962cc52b42f98788fd3608c71e363002c66f4384a159211219decd"
    end
    on_arm do
      url "https://github.com/crazzyghost/nuntius/releases/download/v#{version}/nuntius_#{version}_darwin_arm64.tar.gz"
      sha256 "57b5e4ac06fe84e67a792232412994b177ffa47248c995ed7faa970453a5dfe3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crazzyghost/nuntius/releases/download/v#{version}/nuntius_#{version}_linux_amd64.tar.gz"
      sha256 "224e6960c59630a7f9625512bd77919bead476ae630cefb3fd8a63b8a0e9100f"
    end
    on_arm do
      url "https://github.com/crazzyghost/nuntius/releases/download/v#{version}/nuntius_#{version}_linux_arm64.tar.gz"
      sha256 "b92b8291ca9aab96a5be4684e5b681a35ce1458fb920a2831c70045350ecb482"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nuntius"]
    end
  end

  # No zap stanza required
end
