# This file was generated by GoReleaser. DO NOT EDIT.
cask "nuntius" do
  name "nuntius"
  desc "AI-powered commit message generator TUI"
  homepage "https://github.com/crazzyghost/nuntius"
  version "0.0.0-alpha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nuntius"

  on_macos do
    on_intel do
      url "https://github.com/crazzyghost/nuntius/releases/download/v#{version}/nuntius_#{version}_darwin_amd64.tar.gz"
      sha256 "1ba8dda80873d8cc21c3684fcd70407058568f7f2acf36bf8c77e1694842019f"
    end
    on_arm do
      url "https://github.com/crazzyghost/nuntius/releases/download/v#{version}/nuntius_#{version}_darwin_arm64.tar.gz"
      sha256 "51cb004d3dcb84c203624c4e6441508655bd1b27190e86e632444a1ba6387c23"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crazzyghost/nuntius/releases/download/v#{version}/nuntius_#{version}_linux_amd64.tar.gz"
      sha256 "d5942ecaf4f9c794135e27116b92028127ff285901bd678f7628888f6ab4a5a2"
    end
    on_arm do
      url "https://github.com/crazzyghost/nuntius/releases/download/v#{version}/nuntius_#{version}_linux_arm64.tar.gz"
      sha256 "2d5078644307433c33c26ca9f8cda1e93dae9e7e3fdf8920c2aa3328704ea642"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nuntius"]
    end
  end

  # No zap stanza required
end
